const WORLD_SIZE = 512 * 2000
const EARTH_RADIUS = 6371008.8
const EARTH_CIRCUMFERENCE = 2 * Math.PI * EARTH_RADIUS
const DEG2RAD = Math.PI / 180
const RAD2DEG = 180 / Math.PI
const PROJECTION_WORLD_SIZE = WORLD_SIZE / EARTH_CIRCUMFERENCE
const TILE_SIZE = 512
export {
  DEG2RAD,
  EARTH_CIRCUMFERENCE,
  EARTH_RADIUS,
  PROJECTION_WORLD_SIZE,
  RAD2DEG,
  TILE_SIZE,
  WORLD_SIZE,
}
