const WORLD_SIZE = 512 * 2000
const EARTH_RADIUS = 6371008.8
const EARTH_CIRCUMFERENCE = 2 * Math.PI * EARTH_RADIUS
const DEG2RAD = Math.PI / 180
const RAD2DEG = 180 / Math.PI
const PROJECTION_WORLD_SIZE = WORLD_SIZE / EARTH_CIRCUMFERENCE

export {
  WORLD_SIZE,
  EARTH_RADIUS,
  EARTH_CIRCUMFERENCE,
  DEG2RAD,
  RAD2DEG,
  PROJECTION_WORLD_SIZE,
}
